In [64]:
!pip install db-dtypes

Requirement already satisfied: db-dtypes in c:\users\vinic\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: packaging>=17.0 in c:\users\vinic\anaconda3\lib\site-packages (from db-dtypes) (21.3)
Requirement already satisfied: numpy>=1.16.6 in c:\users\vinic\anaconda3\lib\site-packages (from db-dtypes) (1.23.5)
Requirement already satisfied: pandas>=0.24.2 in c:\users\vinic\anaconda3\lib\site-packages (from db-dtypes) (1.4.4)
Requirement already satisfied: pyarrow>=3.0.0 in c:\users\vinic\anaconda3\lib\site-packages (from db-dtypes) (12.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\vinic\anaconda3\lib\site-packages (from packaging>=17.0->db-dtypes) (3.0.9)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vinic\anaconda3\lib\site-packages (from pandas>=0.24.2->db-dtypes) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vinic\anaconda3\lib\site-packages (from pandas>=0.24.2->db-dtypes) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\vinic\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.24.2->db-dtypes) (1.16.0)

In [1]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

In [2]:
import pandas_gbq
import db_dtypes

In [3]:
credentials = service_account.Credentials.from_service_account_file( filename='e-comerce-388402-2871624f6839.json', 
                                                                    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)

In [4]:
query = """
    select * from Vendas.Vendas2

"""

In [6]:
df = pd.read_gbq(credentials=credentials,query=query)

In [7]:
df

,ID_Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID_Vendedor,Comiss__o__Percentual_,Data_Venda,ValorVenda,Custo
0,SKU-0000325,Morotola Moto G5,Celulares,Doméstico,Motorola,R1298,Campos,Rio de Janeiro,André Pereira,1002,2,2015-03-02,123000,12000
1,SKU-0000326,Morotola Moto G5,Celulares,Doméstico,Motorola,R1298,Campos,Rio de Janeiro,Maria Fernandes,1001,2,2015-04-02,123000,12000
2,SKU-0000327,Morotola Moto G5,Celulares,Doméstico,Motorola,R1298,Campos,Rio de Janeiro,Maria Fernandes,1001,2,2015-05-02,123000,12000
3,SKU-0000171,Samsung Galaxy 8,Celulares,Corporativo,Samsung,S6543,Osasco,São Paulo,André Pereira,1002,2,2015-03-02,399900,12000
4,SKU-0000172,Samsung Galaxy 8,Celulares,Corporativo,Samsung,S6543,Osasco,São Paulo,André Pereira,1002,2,2015-04-02,399900,12000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,SKU-0000451,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-07-21,80000,12000
453,SKU-0000453,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-09-23,85000,12000
454,SKU-0000454,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-10-24,67800,12000
455,SKU-0000456,Geladeira Duplex,Eletrodomésticos,Doméstico,LG,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-11-26,123400,12000
456,SKU-0000457,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-11-27,123400,12000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Produto              457 non-null    object
 1   Produto                 457 non-null    object
 2   Categoria               457 non-null    object
 3   Segmento                457 non-null    object
 4   Fabricante              457 non-null    object
 5   Loja                    457 non-null    object
 6   Cidade                  457 non-null    object
 7   Estado                  457 non-null    object
 8   Vendedor                457 non-null    object
 9   ID_Vendedor             457 non-null    Int64
 10  Comiss__o__Percentual_  457 non-null    Int64
 11  Data_Venda              457 non-null    dbdate
 12  ValorVenda              457 non-null    Int64
 13  Custo                   457 non-null    Int64
dtypes: Int64(4), dbdate(1), object(9)
memory usage: 51.9+ KB