In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.ensemble import ExtraTreesClassifier

In [4]:
df = pd.read_csv('wine_dataset.csv')

In [5]:
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [6]:
#Transformando as variaveis de texto para numericos
df['style'] = df['style'].replace('red', 0)
df['style'] = df['style'].replace('white', 1)

In [7]:
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [9]:
#Separando as variaveis que serão usadas para prever e outras para alvo
y = df['style']
x = df.drop('style', axis = 1)

In [10]:
#Pegando uma parte do dataset para treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [12]:
#Criando modelo
modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#Imrimindo resultado
resultado = modelo.score(x_teste, y_teste)
print('Acurácia:', resultado)

Acurácia: 0.9943589743589744

In [14]:
y_teste[300:304]

2965    1
5856    1
5734    1
693     0
Name: style, dtype: int64

In [15]:
x_teste[300:304]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2965,7.0,0.14,0.41,0.9,0.037,22.0,95.0,0.99140,3.25,0.43,10.9,6
5856,5.8,0.32,0.23,1.5,0.033,39.0,121.0,0.98870,2.96,0.35,12.0,5
5734,5.9,0.26,0.24,2.4,0.046,27.0,132.0,0.99234,3.63,0.73,11.3,5
693,9.0,0.48,0.32,2.8,0.084,21.0,122.0,0.99840,3.32,0.62,9.4,5

In [17]:
previsao = modelo.predict(x_teste[300:304])
previsao

array([1, 1, 1, 0], dtype=int64)